openapi: 3.0.0
info:
  title: P2P Energy API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Registra novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201': { description: Usuário criado }
  /api/auth/login:
    post:
      summary: Autentica usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200': { description: Token JWT }
  /api/offers:
    get:
      summary: Lista ofertas ativas
      security: [ bearerAuth: [] ]
      responses:
        '200': { description: Lista de ofertas }
components:
  schemas:
    UserInput:
      type: object
      properties:
        name: { type: string }
        email: { type: string }
        password: { type: string }
        role: { type: string, enum: [PRODUCER,CONSUMER] }
      required: [name,email,password,role]
    LoginInput:
      type: object
      properties:
        email: { type: string }
        password: { type: string }
      required: [email,password]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
